services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres_test
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
        ports:
            - "5432:5432"
        volumes:
            - postgres_test_data:/var/lib/postgresql/data

volumes:
    postgres_test_data: