version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - /c/Users/A/Downloads/Pictometer/data/postgres:/var/lib/postgresql/data
      - /c/Users/A/Downloads/Pictometer/data/init_scripts:/docker-entrypoint-initdb.d
